language: java
jdk:
  - openjdk11

addons:
  sonarcloud:
    organization: "kgrupp-github"
    token:
      secure: "ISJYrFbOKiBZZ05UkVkKG964ZdcFa+wZKyaCluGM9crsE5a9ni+uYBzyvvw3kvDX1W1qOFx0ytWf2+bvuDcrTcQWZ4MzPbuYsdz/iuocQARxcmcfat1t8EBAsweNDMe97pW4aYZ91vbiV77PUies+/CzwGF4aWaO5WccDfXD3dvtSUxOInDFTyyvukk08QOW0667jFajTfuInVjQ2fVBQdCdsUaun2J6wGfWQbkaeYYYa6PJXMX6weiakmoCZMR8ml9cWvHqgXG1r+RNrIlCArMxzKG7ZcWaeZLDfGhMQlJJ2v3NefVjGuDyeVWwJ6a65L8IdERYAvIb/sacnocS+AyFGmwVPoMBz7n3Rl+/T/R36CS2aUT7JjRJGiHq2XxjDlZVSe4ub7FY6lUVctw/22I4KT+NfupYgcq6WmfEgsJ0Rwad7H+3c1EeSHHDNW/jUNmY0HwcKekBNdxgSA1Nq90Rmk4bEdXG9maWdez5BBQcu6BCBrtHxFthbbmhwZ2qi9KM0KG19wsVQezmf5gGcHS9K+GUXd+QwN5rhUONZqvmIw4N/zIl5+nyW+I8xsHkymoHNZJyI/JKcTySYxx1RsFTa+FN6cb8wq9HnBsgommVlcBx5I8vVdcgi8i3gFvmm55j3ZnF3rSfeYtynZU8C2csyXoJKr3hLOfQcELVYos="

before_install:
  - chmod +x gradlew

after_success:
  - ./gradlew jacocoTestReport coveralls
  - ./gradlew sonarqube