package de.kgrupp.nexus.utils.api;

import de.kgrupp.inoksjavautils.transform.JsonUtils;
import de.kgrupp.monads.result.Result;
import de.kgrupp.nexus.utils.api.result.NexusComponentResult;
import org.junit.Test;

import static org.junit.Assert.assertEquals;

public class JsonConversionTest {

    @Test
    public void test() {
        String json = "{\n"
                + "  \"items\": [\n"
                + "    {\n"
                + "      \"id\": \"aXRkLXJlbGVhc2VzOjc2ZDdkN2U0MTg2YTM5MGZiZjk5ZjI4MDU4YTMzMjUy\",\n"
                + "      \"repository\": \"my-releases\",\n"
                + "      \"format\": \"maven2\",\n"
                + "      \"group\": \"com.example\",\n"
                + "      \"name\": \"my-example-lib\",\n"
                + "      \"version\": \"1.2.0\",\n"
                + "      \"assets\": [\n"
                + "        {\n"
                + "          \"downloadUrl\": \"http://localhost:8080/repository/my-releases/com.example/my-example-lib/1.2.0/my-example-lib-1.2.0.jar\",\n"
                + "          \"path\": \"com.example/my-example-lib/1.2.0/my-example-lib-1.2.0.jar\",\n"
                + "          \"id\": \"aXRkLXJlbGVhc2VzOjg1MTM1NjUyYTk3OGJlOWE3NDI0MjI5NmU2NTE4MTgz\",\n"
                + "          \"repository\": \"my-releases\",\n"
                + "          \"format\": \"maven2\",\n"
                + "          \"checksum\": {\n"
                + "            \"sha1\": \"344293d628dea3e6057959edf43bae96dc6141e4\",\n"
                + "            \"md5\": \"385a3a22c60fc3963c0602d5d5e746d5\"\n"
                + "          }\n"
                + "        },\n"
                + "        {\n"
                + "          \"downloadUrl\": \"http://localhost:8080/repository/my-releases/com.example/my-example-lib/1.2.0/my-example-lib-1.2.0.jar.md5\",\n"
                + "          \"path\": \"com.example/my-example-lib/1.2.0/my-example-lib-1.2.0.jar.md5\",\n"
                + "          \"id\": \"aXRkLXJlbGVhc2VzOjEzYjI5ZTQ0OWYwZTNiOGQxYWEwYWU3MWM4MTkxNDU3\",\n"
                + "          \"repository\": \"my-releases\",\n"
                + "          \"format\": \"maven2\",\n"
                + "          \"checksum\": {\n"
                + "            \"sha1\": \"593cbee261627126604ecc35e5b21741c033c72b\",\n"
                + "            \"md5\": \"ad08cedd479248c40dc5c28e00e6a4aa\"\n"
                + "          }\n"
                + "        },\n"
                + "        {\n"
                + "          \"downloadUrl\": \"http://localhost:8080/repository/my-releases/com.example/my-example-lib/1.2.0/my-example-lib-1.2.0.jar.sha1\",\n"
                + "          \"path\": \"com.example/my-example-lib/1.2.0/my-example-lib-1.2.0.jar.sha1\",\n"
                + "          \"id\": \"aXRkLXJlbGVhc2VzOmQ0ODExNzU0MWRjYjg5ZWNkZTA1MWE5YTU5OWJjM2Ix\",\n"
                + "          \"repository\": \"my-releases\",\n"
                + "          \"format\": \"maven2\",\n"
                + "          \"checksum\": {\n"
                + "            \"sha1\": \"138f5a7a685b7b086daf094e84bd622e38834d7b\",\n"
                + "            \"md5\": \"bc998e17aed1509698dfddfa628ee0fd\"\n"
                + "          }\n"
                + "        },\n"
                + "        {\n"
                + "          \"downloadUrl\": \"http://localhost:8080/repository/my-releases/com.example/my-example-lib/1.2.0/my-example-lib-1.2.0.pom\",\n"
                + "          \"path\": \"com.example/my-example-lib/1.2.0/my-example-lib-1.2.0.pom\",\n"
                + "          \"id\": \"aXRkLXJlbGVhc2VzOjBhYjgwYTc0MzkyMWU0MjY5YTM4OGY2MzUxOWI2MDQ4\",\n"
                + "          \"repository\": \"my-releases\",\n"
                + "          \"format\": \"maven2\",\n"
                + "          \"checksum\": {\n"
                + "            \"sha1\": \"0b1006285c9ef0f3965637ceaa113de73c8228be\",\n"
                + "            \"md5\": \"73fb237c3ef59e86c122dcfa2e73a604\"\n"
                + "          }\n"
                + "        },\n"
                + "        {\n"
                + "          \"downloadUrl\": \"http://localhost:8080/repository/my-releases/com.example/my-example-lib/1.2.0/my-example-lib-1.2.0.pom.md5\",\n"
                + "          \"path\": \"com.example/my-example-lib/1.2.0/my-example-lib-1.2.0.pom.md5\",\n"
                + "          \"id\": \"aXRkLXJlbGVhc2VzOmQ0ODExNzU0MWRjYjg5ZWNkNmUyNWMzMzNlOTZiZWQ4\",\n"
                + "          \"repository\": \"my-releases\",\n"
                + "          \"format\": \"maven2\",\n"
                + "          \"checksum\": {\n"
                + "            \"sha1\": \"74277b5d1065561f46e398d24be49786dc878024\",\n"
                + "            \"md5\": \"d2a28e34de1843d56ebb74d72aba2f62\"\n"
                + "          }\n"
                + "        },\n"
                + "        {\n"
                + "          \"downloadUrl\": \"http://localhost:8080/repository/my-releases/com.example/my-example-lib/1.2.0/my-example-lib-1.2.0.pom.sha1\",\n"
                + "          \"path\": \"com.example/my-example-lib/1.2.0/my-example-lib-1.2.0.pom.sha1\",\n"
                + "          \"id\": \"aXRkLXJlbGVhc2VzOjg1MTM1NjUyYTk3OGJlOWE1MWRkNGJhYzYzMDU5YWY5\",\n"
                + "          \"repository\": \"my-releases\",\n"
                + "          \"format\": \"maven2\",\n"
                + "          \"checksum\": {\n"
                + "            \"sha1\": \"fd46f72140113399eca554fc6d7f1a30e93da7e1\",\n"
                + "            \"md5\": \"f49ca371b042d0e42535667b9010f11a\"\n"
                + "          }\n"
                + "        }\n"
                + "      ]\n"
                + "    },\n"
                + "    {\n"
                + "      \"id\": \"aXRkLXJlbGVhc2VzOjFjNzg3YTAzZGI4MjA5ZWIxZmUwNTZmOTg4ZTdmMGE3\",\n"
                + "      \"repository\": \"my-releases\",\n"
                + "      \"format\": \"maven2\",\n"
                + "      \"group\": \"com.example\",\n"
                + "      \"name\": \"my-example-lib\",\n"
                + "      \"version\": \"1.2.3\",\n"
                + "      \"assets\": [\n"
                + "        {\n"
                + "          \"downloadUrl\": \"http://localhost:8080/repository/my-releases/com.example/my-example-lib/1.2.3/my-example-lib-1.2.3.jar\",\n"
                + "          \"path\": \"com.example/my-example-lib/1.2.3/my-example-lib-1.2.3.jar\",\n"
                + "          \"id\": \"aXRkLXJlbGVhc2VzOmQ0ODExNzU0MWRjYjg5ZWNjMDljMGNhMzJhYmE4ZWIx\",\n"
                + "          \"repository\": \"my-releases\",\n"
                + "          \"format\": \"maven2\",\n"
                + "          \"checksum\": {\n"
                + "            \"sha1\": \"344293d628dea3e6057959edf43bae96dc6141e4\",\n"
                + "            \"md5\": \"385a3a22c60fc3963c0602d5d5e746d5\"\n"
                + "          }\n"
                + "        },\n"
                + "        {\n"
                + "          \"downloadUrl\": \"http://localhost:8080/repository/my-releases/com.example/my-example-lib/1.2.3/my-example-lib-1.2.3.jar.md5\",\n"
                + "          \"path\": \"com.example/my-example-lib/1.2.3/my-example-lib-1.2.3.jar.md5\",\n"
                + "          \"id\": \"aXRkLXJlbGVhc2VzOjBhYjgwYTc0MzkyMWU0MjYxMTc5Mjk3YzhhMjJlMjI2\",\n"
                + "          \"repository\": \"my-releases\",\n"
                + "          \"format\": \"maven2\",\n"
                + "          \"checksum\": {\n"
                + "            \"sha1\": \"593cbee261627126604ecc35e5b21741c033c72b\",\n"
                + "            \"md5\": \"ad08cedd479248c40dc5c28e00e6a4aa\"\n"
                + "          }\n"
                + "        },\n"
                + "        {\n"
                + "          \"downloadUrl\": \"http://localhost:8080/repository/my-releases/com.example/my-example-lib/1.2.3/my-example-lib-1.2.3.jar.sha1\",\n"
                + "          \"path\": \"com.example/my-example-lib/1.2.3/my-example-lib-1.2.3.jar.sha1\",\n"
                + "          \"id\": \"aXRkLXJlbGVhc2VzOjEzYjI5ZTQ0OWYwZTNiOGQ2YTc2MTBlMTMwNTRlMGZl\",\n"
                + "          \"repository\": \"my-releases\",\n"
                + "          \"format\": \"maven2\",\n"
                + "          \"checksum\": {\n"
                + "            \"sha1\": \"138f5a7a685b7b086daf094e84bd622e38834d7b\",\n"
                + "            \"md5\": \"bc998e17aed1509698dfddfa628ee0fd\"\n"
                + "          }\n"
                + "        },\n"
                + "        {\n"
                + "          \"downloadUrl\": \"http://localhost:8080/repository/my-releases/com.example/my-example-lib/1.2.3/my-example-lib-1.2.3.pom\",\n"
                + "          \"path\": \"com.example/my-example-lib/1.2.3/my-example-lib-1.2.3.pom\",\n"
                + "          \"id\": \"aXRkLXJlbGVhc2VzOjg1MTM1NjUyYTk3OGJlOWFmZTRmYjE1YTVmZGZlZWM2\",\n"
                + "          \"repository\": \"my-releases\",\n"
                + "          \"format\": \"maven2\",\n"
                + "          \"checksum\": {\n"
                + "            \"sha1\": \"fe1fb93c4d12879f0eb50eae641dd2affce2a7c3\",\n"
                + "            \"md5\": \"643f20cac318e5845f86a916d37fde22\"\n"
                + "          }\n"
                + "        },\n"
                + "        {\n"
                + "          \"downloadUrl\": \"http://localhost:8080/repository/my-releases/com.example/my-example-lib/1.2.3/my-example-lib-1.2.3.pom.md5\",\n"
                + "          \"path\": \"com.example/my-example-lib/1.2.3/my-example-lib-1.2.3.pom.md5\",\n"
                + "          \"id\": \"aXRkLXJlbGVhc2VzOjEzYjI5ZTQ0OWYwZTNiOGQ1YTdhOTRhOGI4YjI5Mzhk\",\n"
                + "          \"repository\": \"my-releases\",\n"
                + "          \"format\": \"maven2\",\n"
                + "          \"checksum\": {\n"
                + "            \"sha1\": \"c1d54896122f4071b98b8d197c2fbec6ef327170\",\n"
                + "            \"md5\": \"6bf1864bed169e327ad1a2366f9c891a\"\n"
                + "          }\n"
                + "        },\n"
                + "        {\n"
                + "          \"downloadUrl\": \"http://localhost:8080/repository/my-releases/com.example/my-example-lib/1.2.3/my-example-lib-1.2.3.pom.sha1\",\n"
                + "          \"path\": \"com.example/my-example-lib/1.2.3/my-example-lib-1.2.3.pom.sha1\",\n"
                + "          \"id\": \"aXRkLXJlbGVhc2VzOmQ0ODExNzU0MWRjYjg5ZWNkZGE3ZTQxZjdmYmNlYzg4\",\n"
                + "          \"repository\": \"my-releases\",\n"
                + "          \"format\": \"maven2\",\n"
                + "          \"checksum\": {\n"
                + "            \"sha1\": \"ebcf4a2d5c0ef5d194169f49630a19f4aa1faeb0\",\n"
                + "            \"md5\": \"2cf5a5c0824b09c7986107888a0705d2\"\n"
                + "          }\n"
                + "        }\n"
                + "      ]\n"
                + "    }\n"
                + "  ],\n"
                + "  \"continuationToken\": \"35303a64393030\"\n"
                + "}";
        Result<NexusComponentResult> result = JsonUtils.convertToObject(json, NexusComponentResult.class);
        NexusComponentResult nexusComponentResult = result.orElseThrow();
        assertEquals("35303a64393030", nexusComponentResult.getContinuationToken());
    }
}